# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),distribution)
  GLFW_config = distribution
  GLAD_config = distribution
  ImGUI_config = distribution
  Velkro_config = distribution
  Runtime_config = distribution
endif
ifeq ($(config),release)
  GLFW_config = release
  GLAD_config = release
  ImGUI_config = release
  Velkro_config = release
  Runtime_config = release
endif
ifeq ($(config),debug)
  GLFW_config = debug
  GLAD_config = debug
  ImGUI_config = debug
  Velkro_config = debug
  Runtime_config = debug
endif

PROJECTS := GLFW GLAD ImGUI Velkro Runtime

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Velkro/vendor/glfw -f Makefile config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Velkro/vendor/glad -f Makefile config=$(GLAD_config)
endif

ImGUI:
ifneq (,$(ImGUI_config))
	@echo "==== Building ImGUI ($(ImGUI_config)) ===="
	@${MAKE} --no-print-directory -C Velkro/vendor/imgui -f Makefile config=$(ImGUI_config)
endif

Velkro:
ifneq (,$(Velkro_config))
	@echo "==== Building Velkro ($(Velkro_config)) ===="
	@${MAKE} --no-print-directory -C Velkro -f Makefile config=$(Velkro_config)
endif

Runtime: Velkro ImGUI GLFW GLAD
ifneq (,$(Runtime_config))
	@echo "==== Building Runtime ($(Runtime_config)) ===="
	@${MAKE} --no-print-directory -C Runtime -f Makefile config=$(Runtime_config)
endif

clean:
	@${MAKE} --no-print-directory -C Velkro/vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Velkro/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Velkro/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Velkro -f Makefile clean
	@${MAKE} --no-print-directory -C Runtime -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  distribution"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo "   ImGUI"
	@echo "   Velkro"
	@echo "   Runtime"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"